name: "Update NPM Packages"
description: "Update NPM Packages"
inputs:
  repo:
    required: true
    description: "Repository name (e.g., backbase-rnd/code-stats)"
# outputs:
#   ai_labels_string:
#     description: "Assigned AI labels as a comma-separated string"
#     value: ${{ steps.set_outputs.outputs.ai_labels_string }}
runs:
  using: 'composite'
  steps:
    - run: chmod +x ${{ github.action_path }}/main.sh
      shell: bash

    - run: |
        ${{ github.action_path }}/main.sh
      shell: bash
      env:
        REPO_NAME: ${{ inputs.repo }}
        PR_NUMBER: ${{ inputs.pr_number }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        AI_LABELS: ${{ inputs.labels }}

    - name: Debug Assigned Labels
      run: cat assigned_labels.txt
      shell: bash

    - id: set_outputs  # Ensure output is correctly set
      run: |
        AI_LABELS_STRING=$(cat assigned_labels.txt)
        echo "ai_labels_string=$AI_LABELS_STRING" >> $GITHUB_ENV
        echo "ai_labels_string=$AI_LABELS_STRING" >> $GITHUB_OUTPUT
      shell: bash
