name: "Update NPM Packages"
description: "Update NPM Packages"
inputs:
  repo:
    required: true
    description: "Repository name (e.g., backbase-rnd/code-stats)"
# outputs:
#   ai_labels_string:
#     description: "Assigned AI labels as a comma-separated string"
#     value: ${{ steps.set_outputs.outputs.ai_labels_string }}
runs:
  using: 'composite'
  steps:
    - name: Debug
      run: |
        echo "github.action_path: ${{ github.action_path }}"
        echo "--------------------------------"
        ls -la ${{ github.action_path }}
    - name: Try to run js script
      uses: actions/github-script@v7
      with:
        script: |
          try {
          const script = require('${{ github.action_path }}/test.js');
          await script({github, context});
          
          } catch (error) {
            console.error(error);
          }
