# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "main", "release/*", "release/**/*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      shell: bash
      run: |
        mkdir -p dist
        echo "build" >> dist/build.txt

    - uses: docker/metadata-action@v5
      with:
        images: backbaseregistry.azurecr.io/business-usa
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=sha
        flavor: |
          suffix={{date 'YYYYMMDD-HHmmss'}}
      env:
        DOCKER_METADATA_PR_HEAD_SHA: true
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        path: dist/
        name: build-app


    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ matrix.node-version }}
    #     cache: 'npm'
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
