name: Reusable Workflow

on:
  workflow_call:
    inputs:
      dry_run:
        type: boolean
        required: true

env:
  SOME_ENV: ${{ inputs.dry_run && 'dry' || 'prod }}

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | sort
        shell: bash
  
      - uses: actions/github-script@v5
        with:
          script: |
             console.log('==========');
             console.log(JSON.stringify(context, null, 2));
             console.log('==========');

    
