name: Reusable Workflow

on:
  workflow_call:
    inputs:
      dry_run:
        type: boolean
        required: true

env:
  FOO: "foo"
  BAR: "bar"
  SOME_ENV: ${{ inputs.dry_run && env.FOO || env.BAR }}

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/metadata@v5
        with:
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true
      - run: printenv | sort
        shell: bash
  
      - uses: actions/github-script@v5
        with:
          script: |
             console.log('==========');
             console.log(JSON.stringify(context, null, 2));
             console.log('==========');

    
