on:
  workflow_dispatch:
    inputs:
      run-id:
        type: string
        required: true
        default: '17726817747'
      name:
        type: string
        required: false

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ inputs.run-id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - shell: bash
        run: ls -al
