on:
  workflow_dispatch:

permissions: 
  contents: read
  pull-requests: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - name: Check Token Permissions
        uses: actions/github-script@v8
        if: ${{ false }}
        with:
          script: |
            const { owner, repo } = context.repo;
            const permissions = await github
              .rest
              .actions
              .getGithubActionsDefaultWorkflowPermissionsRepository({ owner, repo });

            console.log('PERMISSIONS');
            console.log(JSON.stringify(permissions, null, 2));

      - name: Check Token Permissions (effective)
        uses: actions/github-script@v8
        with:
          script: |
            const { owner, repo } = context.repo;
      
            const { data } = await github.rest.repos.get({ owner, repo });
       
            console.log("Repository permissions for this token:");
            console.log(JSON.stringify(data.permissions, null, 2));
      - name: Check API
        run: |
          # This outputs the headers/info from the local OIDC runtime
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL"
