name: Test JS Script as File

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run JS Script as File inside github script action
        uses: TomaszKasowicz/release-toil-app/.github/actions/update-npm-packages@main