name: Trigger reusable

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: false
jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      
  trigger:
    uses: ./.github/workflows/reusable.yaml
    with:
      dry_run: ${{ inputs.dry_run }}
