name: Trigger reusable

on:
  workflow_dispatch:

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      
  trigger:
    uses: ./.github/workflows/reusable.yaml
    with:
      dry_run: true
