name: Trigger reusable

on:
  workflow_dispatch:

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      
  trigger:
    uses: TomaszKasowicz/release-toil-app/.github/workflows/reusable.yaml@main
    with:
      dry_run: true
