# .github/workflows/deploy-main.yml
name: Deploy to Production

# THIS IS THE CORRECT TRIGGER
on:
  pull_request:
    types: [closed]
    branches:
      - 'main'

jobs:
  deploy:
    # This condition ensures the job only runs if the PR was actually merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Debug: Print the original and merge commit SHAs"
        shell: bash
        run: |
          echo "PR Head SHA (used for artifact name): ${{ github.event.pull_request.head.sha }}"
          echo "Merge Commit SHA (the new squashed commit): ${{ github.event.pull_request.merge_commit_sha }}"

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          # This correctly uses the original head SHA ('a1b2c3d4') to find the artifact
          name: build-${{ github.event.pull_request.head.sha }}
          path: ./dist

      # ... your deployment steps ...
